.\" Manpage for Pokemon Go! Client
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "09 Dic 2019" "1.0" "pokemonClient man page"
.SH NAME
pokemonClient \- Crea un cliente del juego Pokemon Go!, que interactúa directamente con el usuario
.SH SYNOPSIS
pokemonClientt.py {Direccion IP} {Puerto}
.SH DESCRIPTION
pokemonClient modela un cliente del juego Pokemon Go!

Se necesita autenticación con usuario y contraseña, la cual será requerida en ejecución. Una vez accedido, el usuario podrá ver su pokedex, los pokemones disponibles para captura, y jugar para capturar uno nuevo.

.SH OPTIONS

* Dirección IP a través de la cual se conectará al servidor del juego

* Puerto con el cual se creará el socket junto con la dirección IP

.SH SEE ALSO
pokemonServer(7)
.SH BUGS
No hay bugs conocidos
.SH AUTHOR
Doggos Co. (paes@ciencias.unam.mx) y (at.valderrama@ciencias.unam.mx)
