.\" Manpage for Pokemon Go! Server
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "09 Dic 2019" "1.0" "pokemon-client man page"
.SH NAME
pokemon-client \- Crea un cliente del juego Pokemon Go!, que interactúa directamente con el usuario
.SH SYNOPSIS
pokemon-client.py {Direccion IP} {Puerto}
.SH DESCRIPTION
pokemon-client modela un cliente del juego Pokemon Go!

Se necesita autenticación con usuario y contraseña, la cual será requerida en ejecución. Una vez accedido, el usuario podrá ver su pokedex, los pokemones disponibles para captura, y jugar para capturar uno nuevo.

.SH OPTIONS
Recibe una dirección IP y un puerto, con los cuales se creará una conexión con el servidor del juego.

.SH SEE ALSO
pokemon-client(7)
.SH BUGS
No hay bugs conocidos
.SH AUTHOR
Doggos Co. (paes@ciencias.unam.mx) y (at.valderrama@ciencias.unam.mx)
