.\" Manpage for Pokemon Go! Server
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "09 Dic 2019" "1.0" "pokemonServer man page"
.SH NAME
pokemonServer \- Crea un servidor del juego Pokemon Go!
.SH SYNOPSIS
pokemonServer.py {Dirección IP}
.SH DESCRIPTION
pokemonServer modela un servidor del juego Pokemon Go!
.SH OPTIONS
* Dirección IP a través de la cual se conectará con los clientes
.SH SEE ALSO
pokemonClient(7)
.SH BUGS
No hay bugs conocidos
.SH AUTHOR
Doggos Co. (paes@ciencias.unam.mx) y (at.valderrama@ciencias.unam.mx)
