#!/bin/bash

echo Contraseña del usuario root:
mysql -u root -p < create_user.sql

echo Contraseña del usuario doggos: doggos2020
mysql -u doggos -p < create_database.sql;

mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Pokemon.sql

mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Pokedex.sql

mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Usuario.sql
