#!/bin/bash

opcion=$1
rutaMan=/usr/share/man/man7
rutaRoot=$(pwd)

if [ "$opcion" == "-i" ]
    then echo Instalación del manual del servidor en Linux... ;
        echo . ;
        echo . ;
        echo . ; 

        sudo cp server.7.gz $rutaMan ;

        sudo mandb ;

        echo Instalación de la base de datos TCP201-Pokemon... ;

        echo Contraseña del usuario root: ; 
        mysql -u root -p < create_user.sql ;

        echo Contraseña del usuario doggos: doggos2020 ;
        mysql -u doggos -p < create_database.sql ;

        mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Pokemon.sql ;

        mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Pokedex.sql ;

        mysql -u doggos -p -D TCP201-Pokemon < TCP201-Pokemon_Usuario.sql ;
        
        echo Instalación de dependencias de Python ;
        pip install mysql-connector-python ;
        pip install sockets ;
        pip install threaded ;
        

        echo Ejecución del servidor... ; 
        cd ..
        ./pokemonServer.py ;
        
    elif ["$opcion" == "-d"]
        then echo Eliminando el manual de Linux ... 
            cd $rutaMan ;
            sudo rm server.7.gz ;
        
            cd $rutaRoot
            echo Desinstalando base de datos TCP201-Pokemon...
            echo Contraseña del usuario doggos: doggos2020 ;
            mysql -u doggos -p < delete_database.sql ;
    else
        echo Uso para instalar sevidor: ./make_servidor -i
        echo Uso para desinstalar servidor: ./make_servidor -d
        
        
fi


