#!/bin/bash

opcion=$1
rutaMan=/usr/share/man/man7
rutaRoot=$(pwd)

if [ "$opcion" == "-i" ]
    then echo Instalación del manual del servidor en Linux... ;
        echo . ;
        echo . ;
        echo . ; 

        sudo cp server.7.gz $rutaMan ;

        sudo mandb ;

        echo Instalación de la base de datos TCP201-Pokemon... ;

        #mysql -u $userDB -p < make_database.sql ;
        sudo mysql < make_database.sql ;
        sudo mysql < create_user.sql ;
        
        echo Instalación de dependencias de Python ;
        pip3 install mysql-connector-python ;
        pip3 install sockets ;
        pip3 install threaded ;
        

        #echo Ejecución del servidor... ; 
        #cd ..
        #./pokemonServer.py ;
        
    elif [ "$opcion" == "-d" ]
        then echo Eliminando el manual de Linux ... 
            cd $rutaMan ;
            sudo rm server.7.gz ;
        
            cd $rutaRoot
            echo Desinstalando base de datos TCP201-Pokemon... ;
#            echo Ingrese el usuario de mysql propietario de la base de datos:

#            read userDB ;

            sudo mysql < delete_database.sql
    else
        echo Uso para instalar sevidor: ./make_servidor -i ;
        echo Uso para desinstalar servidor: ./make_servidor -d ;
        
fi


